server:
  port: 8083

spring:
  application:
    name: rbac-xqr
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: xqr123456
    url: jdbc:mysql://localhost:3306/rbac?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver


 # com/example/springcloudrbac/pojo/dto
mybatis:
  type-aliases-package: com.example.springcloudrbac/pojo/dto
  mapper-locations: classpath:/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone:  http://eureka8080:8080/eureka/ ,http://eureka7070:7070/eureka/
  instance:
    instance-id: you-canot-know-my-url

# 由spring-boot-starter-actuator而来
info:
  app.name: lalala  #项目名字

